name: deploy_adf_uat

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Azure credentials
      uses: azure/CLI@v1
      with:
        azcliversion: 'latest'
        inlineScript: |
          echo '${{ secrets.azure_credentials }}' > ~/.azure/credentials
          az account set --subscription 7da27902-e7a0-43c8-8477-ec270e869815

    - name: Set up Azure Storage account access
      uses: azure/CLI@v1
      with:
        azcliversion: 'latest'
        inlineScript: |
          echo '${{ secrets.AZURE_STORAGE_KEY }}' > ~/.azure/storage_access_key

    - name: Deploy ARM templates to ADF UAT
      uses: azure/arm-deploy@v1
      with:
        resource-group: rg_uat_git
        template: adf_publish/*.json
        parameters: adf_publish/*.parameters.json
        factory-name: adfuatgit
        subscription-id: 7da27902-e7a0-43c8-8477-ec270e869815

    - name: Logout from Azure
      run: az logout
